import "./product-page.css";

export const productDetailStyles = {
  section: "min-h-screen bg-white py-4 md:py-8",
  breadcrumb: "tm-product-breadcrumb",
  main: "tm-product-main",
  gallery: "tm-product-gallery",
  galleryMain: "tm-gallery-main",
  galleryThumbs: "tm-gallery-thumbs",
  thumb: "tm-thumb",
  thumbActive: "tm-thumb active",
  thumbMore: "tm-thumb tm-thumb-more",
  galleryModal: "tm-gallery-modal",
  galleryModalOpen: "tm-gallery-modal open",
  galleryModalClose: "tm-gallery-modal-close",
  galleryModalInner: "tm-gallery-modal-inner",
  galleryModalItem: "tm-gallery-modal-item",
  info: "tm-product-info",
  heading: "tm-product-heading",
  priceBlock: "tm-product-price-block",
  priceMain: "tm-product-price-main",
  priceCompare: "tm-product-price-compare",
  savings: "tm-product-savings badge-pulse",
  variantWrap: "tm-variant-wrap",
  variantLabel: "tm-variant-label",
  variantOptions: "tm-variant-options",
  sizeBtn: "tm-size-btn",
  sizeBtnActive: "tm-size-btn active",
  qtyWrap: "tm-qty-wrap",
  qtySelector: "tm-qty-selector",
  qtyBtn: "tm-qty-btn",
  qtyInput: "tm-qty-input",
  stockBadge: "text-[13px] text-[#27ae60] font-semibold flex items-center gap-1",
  atcRow: "tm-atc-row",
  atcBtn: "tm-atc-btn",
  wishBtn: "tm-pdp-wish-btn",
  wishBtnActive: "tm-pdp-wish-btn active",
  buyBtn: "tm-buy-btn",
  meta: "tm-product-meta",
  descRow: "tm-product-description-row",
  accordion: "pd-acc",
  accItem: "pd-acc-item",
  accItemOpen: "pd-acc-item open",
  accBtn: "pd-acc-btn",
  accArrow: "pd-acc-arrow",
  accBody: "pd-acc-body",
  descText: "pd-desc-text",
  descGallery: "pd-desc-gallery",
  descMainWrap: "pd-desc-main-wrap",
  descMainImg: "pd-desc-main-img",
  descThumbs: "pd-desc-thumbs",
  descThumb: "pd-desc-thumb",
  descThumbActive: "pd-desc-thumb active",
  descLightbox: "pd-desc-lightbox",
  descLightboxOpen: "pd-desc-lightbox open",
  descLbClose: "pd-desc-lb-close",
  shareWrap: "tm-share-wrap",
  shareBtn: "tm-share-btn",
  shareIcon: "tm-share-icon",
  shareOverlay: "tm-sm-overlay",
  shareOverlayOpen: "tm-sm-overlay open",
  shareModal: "tm-sm-modal",
  shareHead: "tm-sm-head",
  shareTitle: "tm-sm-title",
  shareClose: "tm-sm-close",
  sharePreview: "tm-sm-preview",
  sharePrevImg: "tm-sm-prev-img",
  sharePrevName: "tm-sm-prev-name",
  sharePrevPrice: "tm-sm-prev-price",
  shareGrid: "tm-sm-grid",
  shareOpt: "tm-sm-opt",
  shareIco: "tm-sm-ico",
  shareLbl: "tm-sm-lbl",
  shareCopy: "tm-sm-copy",
  shareCopyUrl: "tm-sm-copy-url",
  shareCopyLbl: "tm-sm-copy-lbl",
  recsSection: "tm-recs-section",
  recsHeading: "tm-recs-heading",
  recsGrid: "tm-recs-grid",
  recsViewAllWrap: "tm-recs-viewall-wrap",
  recsViewAll: "tm-recs-viewall",
};
